[package]
name = "rust-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.4"
nalgebra = "0.31.1"
fastrand = "1.8.0"
indicatif = "0.17.1"
yaml-rust = "0.4.5"

[profile.release]
debug = true
